# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/p261985/public_html/proyectodaw/
#     - /bin/cp -R config/ $DEPLOYPATH
#     - /bin/cp -R controller/ $DEPLOYPATH
#     - /bin/cp -R model/ $DEPLOYPATH
#     - /bin/cp -R view/ $DEPLOYPATH
#     - /bin/cp .cpanel.yml $DEPLOYPATH
#     - /bin/cp .gitignore $DEPLOYPATH
#     - /bin/cp index.php $DEPLOYPATH
#     - /bin/cp README.md $DEPLOYPATH